-- MySQL Script generated by MySQL Workbench
-- 04/29/15 10:43:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mph
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mph
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mph` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mph` ;

-- -----------------------------------------------------
-- Table `mph`.`ciclos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`ciclos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT(1) NULL,
  `anio` INT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`facultades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`facultades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NULL,
  `nombre` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`carreras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NULL,
  `nombre` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL,
  `facultade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `facultades_id_idx` (`facultade_id` ASC),
  CONSTRAINT `facultades_id`
    FOREIGN KEY (`facultade_id`)
    REFERENCES `mph`.`facultades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`catedraticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`catedraticos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`asignaturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(3) NULL,
  `codigo` VARCHAR(45) NULL,
  `nombre` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL,
  `carrera_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `carreras_id1_idx` (`carrera_id` ASC),
  CONSTRAINT `carreras_id1`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `mph`.`carreras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`tipoaulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`tipoaulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`aulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `estado` TINYINT(1) NULL,
  `tipoaula_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipoaulas_id1_idx` (`tipoaula_id` ASC),
  CONSTRAINT `tipoaulas_id1`
    FOREIGN KEY (`tipoaula_id`)
    REFERENCES `mph`.`tipoaulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`dias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`dias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`horarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora` VARCHAR(45) NULL,
  `periodo` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mph`.`asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mph`.`asignaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ocupado` TINYINT(1) NULL,
  `estado` TINYINT(1) NULL,
  `ciclo_id` INT NOT NULL,
  `aula_id` INT NOT NULL,
  `dia_id` INT NOT NULL,
  `horario_id` INT NOT NULL,
  `asignatura_id` INT NOT NULL,
  `catedratico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ciclos_id1_idx` (`ciclo_id` ASC),
  INDEX `aulas_id1_idx` (`aula_id` ASC),
  INDEX `dias_id1_idx` (`dia_id` ASC),
  INDEX `horarios_id1_idx` (`horario_id` ASC),
  INDEX `asignaturas_id1_idx` (`asignatura_id` ASC),
  INDEX `catedraticos_id1_idx` (`catedratico_id` ASC),
  CONSTRAINT `ciclos_id1`
    FOREIGN KEY (`ciclo_id`)
    REFERENCES `mph`.`ciclos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aulas_id1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `mph`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dias_id1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `mph`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `horarios_id1`
    FOREIGN KEY (`horario_id`)
    REFERENCES `mph`.`horarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asignaturas_id1`
    FOREIGN KEY (`asignatura_id`)
    REFERENCES `mph`.`asignaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `catedraticos_id1`
    FOREIGN KEY (`catedratico_id`)
    REFERENCES `mph`.`catedraticos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
